### PR TITLE
Added FailCallback optional functionality

### PR DESCRIPTION
**Pull request by engincancan**

### CODE REVIEW

**Comment by avidas** [comment]
Thanks @engincancan , we will look into this

**Comment by Hosar** [comment]
How do we handle when an error occurs?

**Comment by engincancan** [comment]
There is no callbacks on error right now it just log's error to console

**Comment by romk1n** [comment]
@engincancan there is no error from the sdk about it. since sdk only prints those in the console. therefore originally it was just a way of indicating to the developer that their integration with the plugin is not right. in reality you should never get those callbacks since in objective-c those are not asynchronous request.

**Pull request closed without merging**
